<h1>Welcome to Howtos.com</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Titolo</th>
            <th><i class="glyphicon glyphicon-thumbs-up"></i></th>
            <th><i class="glyphicon glyphicon-thumbs-down"></i></th>
            <th width="5%"></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->list as $recepy) { ?>
        <tr>
            <td><strong><a href="<?=$this->url('recepies')?>/<?=$recepy->getId()?>"><?=$recepy->getTitle()?></a></strong></td>
            <td><?=$recepy->getLikes()?></td>
            <td><?=$recepy->getDislikes()?></td>
            <td>
                <a class="btn btn-default" href="<?=$this->url('recepies')?>/<?=$recepy->getId()?>" role="button">leggi</a>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>
