<?php

namespace Application\Entity\Repository;

/**
 * AuthorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorsRepository extends \Doctrine\ORM\EntityRepository
{
}
