<?php

namespace Application\Entity\Repository;

/**
 * RecepiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecepiesRepository extends \Doctrine\ORM\EntityRepository
{
}
